
namespace Loja139;

// Generated by Selenium IDE
//Pacotes = Dependências= Bibliotecas
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;

[TestFixture] // configuração do teste
//Classe
public class ProdutosTest {

  //Atributos = Características = Campos

  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;

  //Funções e Métodos
  [SetUp]
  public void SetUp() {
    new DriverManager().SetUpDriver(new ChromeConfig());
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(10000);
  }
  [TearDown]
  
  protected void TearDown() {
    driver.Quit();
  }
  
  [Test]
  public void produtos() {
    driver.Navigate().GoToUrl("https://www.saucedemo.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1366, 768);
    driver.FindElement(By.CssSelector(".login_wrapper")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"username\"]")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"username\"]")).SendKeys("standard_user");
    driver.FindElement(By.CssSelector("*[data-test=\"password\"]")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"password\"]")).SendKeys("secret_sauce");
    driver.FindElement(By.CssSelector("*[data-test=\"login-button\"]")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".title")).Text, Is.EqualTo("Products"));
    Assert.That(driver.FindElement(By.CssSelector("#item_4_title_link > .inventory_item_name")).Text, Is.EqualTo("Sauce Labs Backpack"));
    Assert.That(driver.FindElement(By.CssSelector(".inventory_item:nth-child(1) .inventory_item_price")).Text, Is.EqualTo("$29.99"));
    driver.FindElement(By.CssSelector("#item_4_title_link > .inventory_item_name")).Click();
    Assert.That(driver.Title, Is.EqualTo("Swag Labs"));
    Assert.That(driver.FindElement(By.CssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).Text, Is.EqualTo("Add to cart"));
    driver.FindElement(By.CssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".shopping_cart_badge")).Text, Is.EqualTo("1"));
  }
}